# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

name: CS

on:
  push:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.x'
      - 'feature/**'
      - 'fix/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.x'

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Code linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Set up pip cache
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt') }}-${{ hashFiles('requirements/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: make install

      - name: Code linting
        run: make lint
        env:
          DJANGO_SETTINGS_MODULE: branch.settings.test
          SECRET_KEY: Naive and not very secret key used for tests
