# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
      - 'fix/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 11 * * *'
      #      | | | | |
      #      | | | | |____ day of the week (0 - 6 or SUN-SAT)
      #      | | | |____ month (1 - 12 or JAN-DEC)
      #      | | |____ day of the month (1 - 31)
      #      | |____ hour (0 - 23)
      #      |____ minute (0 - 59)

env:
  NPM: npm
  PYTHON: python
  PYTHONUNBUFFERED: '1'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-2019
        experimental: [false]
        include:
          - python: '3.10.0-beta - 3.10'
            os: ubuntu-20.04
            experimental: true
          - python: '3.10.0-beta - 3.10'
            os: macos-latest
            experimental: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Prerequisites (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

          # Make sure the development packages of libxml2 and libxslt are
          # installed. This is needed for pyquery.
          if [ "${{ matrix.python }}" = "3.10.0-beta - 3.10" ]; then
            sudo apt-get update --quiet --yes 1>/dev/null
            sudo apt-get install --no-install-recommends -q -y \
              libxml2-dev libxslt-dev
          fi

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(python -m pip cache dir)"

      - name: Set up pip cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Nodejs
        uses: actions/setup-node@v2.3.1
        with:
          node-version: '14'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Set up npm cache
        uses: actions/cache@v2.1.6
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Makefile selftest
        run: make help

      - name: Set up virtualenv
        run: |
          python -m pip install --upgrade pip
          python -m pip --use-feature=in-tree-build install \
            wheel \
            setuptools \
            tox \
            tox-gh-actions
          npm install
          npm install -g sass

      - name: Configuration of the application
        run: cp ./.env.dist ./.env

      - name: Setuptools self-test
        run: |
          python setup.py --fullname
          python setup.py --long-description
          python setup.py --classifiers

      - name: Run unit tests with coverage
        run: tox
        env:
          RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}

      # Use a modern Python version for combining coverage
      - name: Set up Python 3.10
        uses: actions/setup-python@v2.2.2
        if: ${{ matrix.python != '3.10.0-beta - 3.10' }}
        with:
          python-version: '3.10.0-beta - 3.10'

      - name: Combine coverage reports
        run: make ccov

      - name: Upload coverage report
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip --use-feature=in-tree-build install coveralls
          coveralls

      - name: Success Reporting
        if: success()
        run: git log --format=fuller -5
